### ISSUE TITLE
Update tutorial with new VFC_BACKENDS interface

### ISSUE THREAD

**Issue by pablooliveira** [verificarlo/verificarlo#107]
The tutorial should be updated to reflect the recent user interface changes for verificarlo.

**Comment by titeup** [comment]
@pablooliveira  I think we can close that one after IXPUG tutorial release?

**Comment by pablooliveira** [comment]
Indeed, closed :-)

**Comment by titeup** [comment]
I will update the new one with last update of vfc backend option for MCA

**Comment by titeup** [comment]
[main-en.pdf](https://github.com/verificarlo/verificarlo/files/4650158/main-en.pdf)

**Comment by titeup** [comment]
created the link to the new pdf.  @pablooliveira can you review it before we push it on the wiki.
I will do the same with the source code which also changed.

**Comment by titeup** [comment]
can't upload tgz, I'll check with @pablooliveira how to create the link for the wiki

**Comment by titeup** [comment]
[verificarlo-tutorial.pdf](https://github.com/verificarlo/verificarlo/files/4650206/verificarlo-tutorial.pdf)

**Comment by titeup** [comment]
[verificarlo-tutorial.zip](https://github.com/verificarlo/verificarlo/files/4650249/verificarlo-tutorial.zip)

**Comment by titeup** [comment]
zip it will be...

**Comment by titeup** [comment]
But I need to update verificarlo tutorial main-en.tex again to use these last links... update file, limk, pull request, merge and so on...

**Comment by titeup** [comment]
[verificarlo-tutorial.pdf](https://github.com/verificarlo/verificarlo/files/4650876/verificarlo-tutorial.pdf)

**Comment by titeup** [comment]
done, last update on verificarlo-tutorial git asap
