### ISSUE TITLE
Issue in the qnoise function

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#111]
https://github.com/verificarlo/verificarlo/blob/6b86bcd044edbe316a3c766a84f5de5cb2603ea3/src/backends/interflop-mca/interflop_mca.c#L172-L173
The `qnoise` function computes `2^(exp)*d_rand` so if the exponent is 0 we should return `d_rand` instead of 1.

https://github.com/verificarlo/verificarlo/blob/6b86bcd044edbe316a3c766a84f5de5cb2603ea3/src/backends/interflop-mca/interflop_mca.c#L178-L179

**Comment by pablooliveira** [comment]
Good catch :+1:
