### ISSUE TITLE
bug with argument parsing in the backends

### ISSUE THREAD

**Issue by DamDem** [verificarlo/verificarlo#131]
[test.log](https://github.com/verificarlo/verificarlo/files/3891699/test.log)
[config.log](https://github.com/verificarlo/verificarlo/files/3891700/config.log)
I installed verificarlo on my device following the README.md.  After running "make installcheck"  test_ieee_backend failed. I linked the test.log related on this test and the config.log.

**Comment by pablooliveira** [comment]
@DamDem thanks for the report !

@yohanchatelain you mentioned that you also got this bug and knew how to fix it; I'll assign it to you. Thanks :muscle:
