### ISSUE TITLE
Add Coverity report into CI

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#134]
Add [coverity scan](https://scan.coverity.com/github) to 

> Find and fix defects in your Java, C/C++, C#, JavaScript, Ruby, or Python open source project for free

**Comment by pablooliveira** [comment]
Please replace the covery badge on the README.md by the one auto-generated in the github pipeline, once you implement this. Thanks!

**Comment by pablooliveira** [comment]
This seems not possible currently with the coverity pipeline. We will manually update the badge; and test major releases.
