### ISSUE TITLE
Error with llvm-3.3 and llvm-3.4

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#140]
Verificarlo crash during the execution with llvm-3.3 and llvm-3.4.
It seems that a function has been introduced since llvm-3.5 and breaks the execution.
I will provide a full report.

**Comment by yohanchatelain** [comment]
Both versions crash with the same error during the testing.
> Error opening '/home/yohan/local/lib/libvfcinstrument.so': /home/yohan/local/lib/libvfcinstrument.so: undefined symbol: _ZNK4llvm10ModulePass17createPrinterPassERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  -load request ignored.
opt: Unknown command line argument '-vfclibinst'.  Try: '/usr/lib/llvm-3.4/bin/opt -help'
opt: Did you mean '-lint'?

This symbol seems to be there from version llvm-3.5.

--
[test-llvm-3.3.log](https://github.com/verificarlo/verificarlo/files/4204491/test.log)
[config-llvm-3.3.log](https://github.com/verificarlo/verificarlo/files/4204492/config.log)
[config-llvm-3.4.log](https://github.com/verificarlo/verificarlo/files/4204506/config.log)
[test-llvm-3.4.log](https://github.com/verificarlo/verificarlo/files/4204509/test.log)

**Comment by pablooliveira** [comment]
Since #165, 3.3 and 3.4 are unsupported. Closing.
