### ISSUE TITLE
test_unstable_branches fails with llvm-3.9.1

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#145]
It seems to be an error of llvm-3.9.1, see the following [post](http://llvm.1065342.n5.nabble.com/llvm-dev-CloneFunctionInto-produces-invalid-debug-info-td110077.html).
We should perhaps warn the user in the README.md.
--
[config.log](https://github.com/verificarlo/verificarlo/files/4204366/config.log)
[test.log](https://github.com/verificarlo/verificarlo/files/4204367/test.log)

**Comment by pablooliveira** [comment]
Since #165, 3.3 and 3.4 are unsupported. Closing.
