### ISSUE TITLE
Wrong names for float comparisons in interflop_ieee.c?

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#150]
https://github.com/verificarlo/verificarlo/blob/b4988bca5c803f9557d610cbccb2b5690b64aa15/src/backends/interflop-ieee/interflop_ieee.c#L213-L219

**Comment by pablooliveira** [comment]
Hi @yohanchatelain can you explain the problem here, please.

**Comment by yohanchatelain** [comment]
Line 215, the variable `str`is empty, line 219 `str = "FCMP_UGT"` that is different from the above case. Is there a mistake?

**Comment by pablooliveira** [comment]
Ah yes ! This seems indeed a mistake, thanks :-)

**Comment by pablooliveira** [comment]
This has been fixed in your refactoring of ieee backend, closing !
