### ISSUE TITLE
ability to provide arguments in environment variable without spaces?

### ISSUE THREAD

**Issue by gkiar** [verificarlo/verificarlo#154]
Hi!

I'm currently trying to use Verificarlo inside a Singularity container, but there is a bug in their stack that prevents me from providing environment variables on the command-line that contain spaces (see https://github.com/sylabs/singularity/issues/5108). While they work on this, I was wondering if there is any way to specify args for verificarlo that would be compatible with this restriction?

Ideally I'd be using options equivalent to `libinterflop_mca.ieee --mode rr`.

thanks!

**Comment by pablooliveira** [comment]
Dear @gkiar. I'm not sure we can remove spaces from VFC_BACKENDS.
But it seems you can escape the spaces by adding additional quotes as suggested in sylabs/singularity#5108. Would that be acceptable ?
