### ISSUE TITLE
log info in cancellation backend 

### ISSUE THREAD

**Issue by Avaquet** [verificarlo/verificarlo#157]
Hello, 
Just to warn you on the lack of "\n" at the end of the log info in interflop_cancellation.c at the line 209.
` logger_info("interflop_cancellation: loaded backend with tolerance = %d \n", TOLERANCE);`

**Comment by pablooliveira** [comment]
Thanks @Avaquet, do you want to do a PR ?

**Comment by Avaquet** [comment]
not it's not big enough i think

**Comment by pablooliveira** [comment]
Even small fixes are important :rainbow:
