### ISSUE TITLE
LLVM 8?

### ISSUE THREAD

**Issue by roblim1** [verificarlo/verificarlo#163]
I tried installing Verificarlo with LLVM 8.0.1 and 9.0, both compiled with source, but get the following error.  See [config_vfc_llvm8.log](https://github.com/verificarlo/verificarlo/files/4597267/config_vfc_llvm8.log).  Verificarlo with LLVM 4.0.1 (source) works for me.

**Comment by yohanchatelain** [comment]
It seems that `-pthread` flags is missing with version of gcc < 6. As workaround, you could try to add this flag with CFLAGS="-pthread" or use a higher version of gcc. I will look at this more closely.

**Comment by roblim1** [comment]
Thanks for looking into this.  

I tried adding CFLAGS="-pthread" for gcc 5.3, llvm 8 (prebuilt, source), but get the attached errors:
  [config_llvm801p_gcc53.log](https://github.com/verificarlo/verificarlo/files/4625854/config_llvm801p_gcc53.log)
  [config_llvm800s_gcc53.log](https://github.com/verificarlo/verificarlo/files/4625855/config_llvm800s_gcc53.log) 

gcc >= 6 with llvm 8 prebuilt without the above flag gives me the same errors (line 556+ of config_llvm801p_gcc53.log).

**Comment by yohanchatelain** [comment]
Ok, it seems that llvm-6 and above are not compatible with gcc < 6. We will upgrade the requirements, thank you.
However, your config.log said that you used gcc-5.3. Add `CC=gcc-6` during the configure to specify the gcc version. It works for me with gcc-6 and llvm-6 to llvm-9.

**Comment by roblim1** [comment]
With CC=gcc-6, I get this error:  
     [config_llvm801p_gcc64.log](https://github.com/verificarlo/verificarlo/files/4630447/config_llvm801p_gcc64.log)

**Comment by pablooliveira** [comment]
Hi @roblim1. In your output we find the line

```
./configure: line 3725: gcc-6: command not found
```

It seems gcc-6 cannot be found in your PATH.

**Comment by roblim1** [comment]
Not sure if I have gcc-6 as an executable command.

```
-bash-4.2$ module load gcc/6.4 
-bash-4.2$ which gcc
/packages/gcc/6.4/bin/gcc
```
```
-bash-4.2$ echo $PATH
/packages/gcc/6.4/bin:/usr/local/packages/cmake/3.8.2/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
```
```
-bash-4.2$ ls /packages/gcc/6.4/bin
aot-compile  gappletviewer  gcc-nm      gcjh       gfortran    gjavah         grmic         gtnameserv      x86_64-pc-linux-gnu-c++        x86_64-pc-linux-gnu-gcc-ar      x86_64-pc-linux-gnu-gfortran
c++          gc-analyze     gcc-ranlib  gcov       gij         gkeytool       grmid         jcf-dump        x86_64-pc-linux-gnu-g++        x86_64-pc-linux-gnu-gcc-nm
cpp          gcc            gcj         gcov-dump  gjar        gnative2ascii  grmiregistry  jv-convert      x86_64-pc-linux-gnu-gcc        x86_64-pc-linux-gnu-gcc-ranlib
g++          gcc-ar         gcj-dbtool  gcov-tool  gjarsigner  gorbd          gserialver    rebuild-gcj-db  x86_64-pc-linux-gnu-gcc-6.4.0  x86_64-pc-linux-gnu-gcj
```

**Comment by roblim1** [comment]
Should I symlink it?

**Comment by pablooliveira** [comment]
No need to symlink. But configure needs to find the command you pass. If you do not have gcc-6 as a command, then you cannot call configure with "CC=gcc-6". You must use the appropriate path in your system.

**Comment by roblim1** [comment]
Here is the config.log for gcc 6.4:
  [config_llvm801p_gcc64.log](https://github.com/verificarlo/verificarlo/files/4634617/config_llvm801p_gcc64.log)

**Comment by roblim1** [comment]
I was able to build Verificarlo successfully on another machine (clang 8.0.1, gcc 6.4), and 22/26 of the tests pass (looks like paths issues).  The machine I was using previously is on a shared file system with multiple modules, so there may have been conflicts there.  

Thanks all for looking into this!
