### ISSUE TITLE
No support for vector operations longer than the archictecture's vector width

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#164]
The backend for the double4 gives wrong results.
In the following minimal example [test-vecto.zip](https://github.com/verificarlo/verificarlo/files/4728825/test-vecto.zip), I add the value 2 to a vector of 0 for different vector sizes.
For the double4 type, we have arbitrary values.

```bash
VFC_BACKENDS="libinterflop_ieee.so --debug" ./a.out
Info [verificarlo]: loaded backend libinterflop_ieee.so
Info [interflop_ieee]: Decimal 2 + 0 -> 2
Info [interflop_ieee]: Decimal 2 + 0 -> 2
float2[0]=2.000000
float2[1]=2.000000

Info [interflop_ieee]: Decimal 2 + 0 -> 2
Info [interflop_ieee]: Decimal 2 + 0 -> 2
double2[0]=2.000000
double2[1]=2.000000

Info [interflop_ieee]: Decimal 2 + 0 -> 2
Info [interflop_ieee]: Decimal 2 + 0 -> 2
Info [interflop_ieee]: Decimal 2 + 0 -> 2
Info [interflop_ieee]: Decimal 2 + 0 -> 2
float4[0]=2.000000
float4[1]=2.000000
float4[2]=2.000000
float4[3]=2.000000

Info [interflop_ieee]: Decimal 6.95293e-310 + 2.08323e-317 -> 6.95293e-310
Info [interflop_ieee]: Decimal 0 + 6.95293e-310 -> 6.95293e-310
Info [interflop_ieee]: Decimal 0 + 6.95293e-310 -> 6.95293e-310
Info [interflop_ieee]: Decimal 6.90958e-310 + 2.07517e-317 -> 6.90958e-310
double4[0]=0.000000
double4[1]=0.000000
double4[2]=0.000000
double4[3]=0.000000
```
When I compile with `clang` the code is working.
```bash
float2[0]=2.000000
float2[1]=2.000000

double2[0]=2.000000
double2[1]=2.000000

float4[0]=2.000000
float4[1]=2.000000
float4[2]=2.000000
float4[3]=2.000000

double4[0]=2.000000
double4[1]=2.000000
double4[2]=2.000000
double4[3]=2.000000
```
I suspect the compiler to pass the vector by reference since it is to wide.
So we have a pointer instead of a value.

**Comment by pablooliveira** [comment]
> I suspect the compiler to pass the vector by reference since it is to wide.
> So we have a pointer instead of a value.

Interesting. If that is the case it should be possible to fix. I will try to have a look soon.

**Comment by pablooliveira** [comment]
@yohanchatelain has shown that the problem triggers because his system does not have AVX instruction set. Therefore when forcing a size 4 vector with `typedef double double4 __attribute__((ext_vector_type(4)));` or other means on an architecture that does not support such vector width; the vector cannot be passed as a register.

clang is able to handle those cases by passing the vector as a pointer instead. 
Since forcing a vector type to an unsuported width is a rare corner case that requires attributes or intrincsins, we have agreed for now to avoid those cases in Verificarlo.

Yet it would be nice to report an error message in the verificarlo instrumentation pass when we see a vector type wider than the maximum width supported in the target architecture.

**Comment by Sholde** [comment]
Hello,
I have AVX instruction set on my architecture and even if I compile a program with **double4** type and `-mavx` or `-march=native` flags for Verificarlo compiler, this give wrong result for all backends.

**Comment by pablooliveira** [comment]
@Sholde could you please tell us which architecture you are using here ?

**Comment by Sholde** [comment]
I am on Virtual Machine with Manjaro linux distribution based on Archlinux where I use 4 of 6 core that I havec on my cpu.

Here my **cpuinfo** file :
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
stepping	: 10
cpu MHz		: 2807.998
cache size	: 9216 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5618.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
stepping	: 10
cpu MHz		: 2807.998
cache size	: 9216 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5618.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
stepping	: 10
cpu MHz		: 2807.998
cache size	: 9216 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5618.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
stepping	: 10
cpu MHz		: 2807.998
cache size	: 9216 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 5618.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

```

For more information, I think Verificarlo use good architecture option flags like `-march=native` because when I use the command : `verificarlo-c --show-cmd main.c -march=native` this show me :

```
/usr/bin//clang -c -S  main.c -emit-llvm '-march=native' -o /home/sholde/dev/master/projet/test/main.vrx09zqh.1.ll
/usr/bin/opt -S  -load /usr/local/lib/libvfcinstrument.so -vfclibinst   /home/sholde/dev/master/projet/test/main.vrx09zqh.1.ll -o /home/sholde/dev/master/projet/test/main.ffe4ggcx.2.ll
/usr/bin//clang -c -o main.o /home/sholde/dev/master/projet/test/main.ffe4ggcx.2.ll '-march=native'
/usr/bin//clang -c -O3 -Wno-varargs -fPIC  -o .vfcwrapper.o /usr/local/bin/../include/vfcwrapper.c -I /usr/local/bin/../include/
/usr/bin//clang  main.o '-march=native' .vfcwrapper.o -rpath /usr/local/lib -L /usr/local/lib -ldl
/usr/bin//clang @/tmp/tmp31y3efxo
```

**Comment by yohanchatelain** [comment]
Hi @Sholde, you should use the same version of clang and llvm, btw verificarlo the last version of clang support by verificarlo is the 10. 
Could you please show your `config.log` file? 
Also could you please test this command `verificarlo-c main.c -O3 -fno-slp-vectorize`?

**Comment by Sholde** [comment]
Hi @yohanchatelain , thanks for your answer, it works with the option `-fno-slp-vectorize` on Verificarlo for all backends except for **double16**. I am going to search why. (I will put my config.log soon)

**Comment by yohanchatelain** [comment]
**Update**: 
This issue causes bug on [fuzzy](https://github.com/verificarlo/fuzzy) package when recompiling numpy (see issue [#34](https://github.com/verificarlo/fuzzy/issues/34)).
After looking at it in details, the bug is caused by a mismatched between functions signature in `vfcwrapper.c` and signatures generated in `libVFCInstrument.cpp`. When `-march=native` is passed as option, `clang` vectorizes vector instructions by using appropriate vector registers. In cases where vector type are not supported by current architecture, those vector are passed by pointer. However, the signature created during instrumentation does not take into account the vectorization or not. For exemple, function `_16xdoubleadd` is:
- `define <16 x double> @_16xdoubleadd(<16 x double>* nocapture readonly byval(<16 x double>) align 128 %0, <16 x double>* nocapture readonly byval(<16 x double>) align 128 %1)` in `vfcwrapper.o`
- `define <16 x double> @_16xdoubleadd(<16 x <16 x double>)  %0, <16 x double> %1)` in `libVFCInstrument.cpp`

I proposed as solution to directly reuse function signatures of `vfcwrapper.c` in `libVFCInstrument.cpp` for avoiding this signature mismatched. I will propose a PR soon to implement this mechanism.
