### ISSUE TITLE
Function instrumentation may fail for intrinsics

### ISSUE THREAD

**Issue by Avaquet** [verificarlo/verificarlo#171]
Compilation can fail when function instrumentation in used. Because parameter attributes are not correct.

**Comment by titeup** [comment]
Hello @Avaquet , I know this is a quite old one, but can you ellaborate the description. At least gives more details/code example to reproduce the issue. Thanks!

**Comment by Avaquet** [comment]
Yes, it's old, it was fixed right after the creation of this issue. Attributes are now cloned during the instrument pass, so it's no longer a problem.

**Comment by pablooliveira** [comment]
Thanks for the feedback, closing !
