### ISSUE TITLE
Rewrite tests_vprec_backends with python-gmp instead of python-bigfloat

### ISSUE THREAD

**Issue by pablooliveira** [verificarlo/verificarlo#180]
To remove a pip dependency.

**Comment by yohanchatelain** [comment]
I just discovered that the [`decimal`](https://docs.python.org/3/library/decimal.html#module-decimal) package is part of the python standard library. That could be a good option to replace `bigfloat` without adding an extra dependency.

**Comment by pablooliveira** [comment]
Yes, in particular, bigfloat requires manual installation with the latest linux distributions which is a hassle. I agree that replacing it with decimal would be nice !

**Comment by titeup** [comment]
@yohanchatelain any updates? Do you plan to do it?

**Comment by yohanchatelain** [comment]
Hi @titeup, I did not work on it and actually it only offers arbitrary precision for Decimal representation so we'll have issue rounding numbers to binary precision. But we could reimplement what we need in pure C MPFR to get rid of bigfloat.

**Comment by yohanchatelain** [comment]
Done with #339.
