### ISSUE TITLE
An undefined reference to 'main' error when I run your tutorial in docker

### ISSUE THREAD

**Issue by xinyi-li7** [verificarlo/verificarlo#187]
I searched a lot and really don't what happened here
![image](https://user-images.githubusercontent.com/69008042/96501745-09e86780-120e-11eb-8134-1d86eb1f329f.png)

**Comment by yohanchatelain** [comment]
Hi,
Thank you for the report. First, we didn't have update the tutorial but now you should use `verificarlo-c` for compiling `C` files.
Moreover, it seems that you are not the in the directory `tchebychev`, do you copy the file into workdir? If not, could you please try the compile command in the `:/workdir/tchebychev` and tell the output?

**Comment by xinyi-li7** [comment]
Hi, thanks for your reply! I think I am in the tchebychev, and I listed all the files here: 
![image](https://user-images.githubusercontent.com/69008042/96507882-0d342100-1217-11eb-9cd1-71b1bd05a589.png)
What's more, I also run the test code on your webpage, and it still rendered the same error. 
![image](https://user-images.githubusercontent.com/69008042/96508201-761b9900-1217-11eb-9f1d-10ecd0bd360c.png)
I am looking forward to your replying!

**Comment by pablooliveira** [comment]
> What's more, I also run the test code on your webpage, and it still rendered the same error.

Hi @xinyi-li7, thanks for your report. I cannot reproduce your bug report with the latest docker image.

In the first output you posted in the first edit of your message, the problem is that the verificarlo command was run outside of the docker image, as shown in your prompt. When using verificarlo through the docker image please ensure that you run commands inside the image.

In the second output could you please check that the contents of `test.c` match the example [here](https://github.com/verificarlo/verificarlo#using-verificarlo-through-its-docker-image)?

**Comment by xinyi-li7** [comment]
I just followed the steps in your readme file: 
![image](https://user-images.githubusercontent.com/69008042/96665894-2cb07400-1313-11eb-8851-3b98e2dfd5db.png)
BTW, I used a MacOS, will it be the issue? But I think we used the container, so I don't think it would be a problem at first.

**Comment by pablooliveira** [comment]
What you did seems indeed correct. The message from the linker indicates he cannot find the `main` function in the compiled object files. I'm not sure what is going on and do not have a MacOS system to reproduce.

Could you please check the output of this command after the above ones:
```
poliveira@ix:~/example$ docker run -v "$PWD":/workdir verificarlo/verificarlo nm test.o
0000000000000000 r .LCPI0_0
                 U _doubleadd
0000000000000000 T main
                 U printf
```

I would like to check that the symbol `main` is present in the generated object file.

Other things you could check is if you use a different locale inside an outside the docker image (utf8).

**Comment by xinyi-li7** [comment]
Hi, I just followed the same steps in a virtual box machine, and it worked. I guess it caused by some unknown conflicts with MacOS.

**Comment by pablooliveira** [comment]
@xinyi-li7: I'm happy it worked for you in the end. Thanks for reporting the problem, we will keep an eye for any strange behavior in MacOS.
