### ISSUE TITLE
Clean tests folder after installcheck

### ISSUE THREAD

**Issue by Sholde** [verificarlo/verificarlo#193]
I think that clean the **tests** folder after check the installation will be nice or at least clean with clean target. (I don't know for the moment how to do it properly)

**Comment by pablooliveira** [comment]
Thanks @Sholde. I agree that this would be nice but it is not easy to do. Indeed, currently tests do not clean after themselves. It is actually useful to have the traces left for inspection when one of the tests breaks.

But I agree, it would be nice to be able to clean tests directory. I can see either adding make clean targets to each test; or changing the tests so they output files to a particular temporary directory.

If you feel like tackling this, a patch is very welcome.

**Comment by yohanchatelain** [comment]
Why don't use `git clean` command?

**Comment by pablooliveira** [comment]
It's indeed a good option; but it relies on git been used; which is not the case for users downloading our `.tar.gz` releases.

We could also use `git` to automatically generate a list of created files and add a single make clean target in `src/tests/`.

**Comment by yohanchatelain** [comment]
Good point, I didn't think about the .tar option. Generate the make clean seems the best solution then.

**Comment by Sholde** [comment]
Hi,

I did a clean target with `git clean` command here : https://github.com/Sholde/verificarlo/commit/90cf2209e480e9127d11e70c0e9d38518dba8d46.
But this method requires to generate a list with all supposed file to clean, but it doesn't clean all file if  certain file was generate only if the test failed (I am not sure that files exist now).
And especially it doesn't clean ignored files (in `.gitignore`). For me it is important to clean them too.

It's for that I did an another method with a `clean.sh` file en each test: https://github.com/Safecarlo/verificarlo/compare/master...Sholde:clean-test.
Each developer can add easily a clean file which is automatically called with the clean target on `tests/` folder.

**Comment by pablooliveira** [comment]
Hi, thanks @Sholde. I prefer the first solution (adding a `clean.sh` to every test is a hassle). To solve the problem with ignored files, we would in addition to your clean list simply remove all `.o` and `.ll` files from `tests/` ? 
Maybe with something like:
```
find . -name '*.o' | xargs -- rm
```
inside `cleantests:` target ?

If you feel up to it, I'll gladly help you merge a pull-request with this. Just submit the PR and tag me or @titeup as a reviewer.

**Comment by pablooliveira** [comment]
Ignore my previous message. After discussion in our team meeting, we have decided that the second solution, while more work is simpler and more robust.

If you want to do a PR for the second solution based around `clean.sh` scripts in tests directories we can merge it.

It would be important to make sure that if the `clean.sh` file is missing, there is no hard failure of the clean script.

**Comment by pablooliveira** [comment]
Closed in #227.
