### ISSUE TITLE
Inconsistency in the way instrumented functions are specified for inclusion/exclusion and --inst-func

### ISSUE THREAD

**Issue by mistoan** [verificarlo/verificarlo#206]
There is an inconsistency between the way in which functions are specified for inclusion/exclusion from verificarlo instrumentation and for the --inst-func option.
For inclusion/exclusion the mangled name is used, but for --inst-func option the un-mangled name is used.

**Comment by Avaquet** [comment]
Indeed, the function instrumentation uses unmangled names, which can be easily changed, but the function instrumentation pass did not manage inclusion/exclusion lists. Again, this can be done, and I think it will be an interesting feature.

**Comment by mistoan** [comment]
> the function instrumentation pass did not manage inclusion/exclusion lists
No it does not.
But the exploration does.
Or at least that's what I understood from the documentation.
`If you're looking for the optimal precision for a set of functions:

./vfc_precexp exrun excmp function_1 function_2 ...
`
So the precision exploration does have it's mechanism for filtering.
At least, from my tests, I get different results when I use this list.

**Comment by pablooliveira** [comment]
We discussed mangling/unmangling around september/october 2020 with @yohanchatelain. I think the agreement was to use only binary names at the low-level. Since mangling depends on language (eg. Fortran/C++ have different mangling conventions).

Therefore I recommend we remove the unmangling call from the function instrumentation. This way we will be consistant and use only the symbol name in the binary (mangled). 

But it would be a good idea in high level tools, such as the one producing reports to have both names.

**Comment by yohanchatelain** [comment]
> We discussed mangling/unmangling around september/october 2020 with @yohanchatelain. I think the agreement was to use only binary names at the low-level. Since mangling depends on language (eg. Fortran/C++ have different mangling conventions).
> 
> Therefore I recommend we remove the unmangling call from the function instrumentation. This way we will be consistant and use only the symbol name in the binary (mangled).
> 
> But it would be a good idea in high level tools, such as the one producing reports to have both names.

I agree, working on mangled name is the safest since some mangled functions cannot be demangled.
We could use `nm` + [llvm-cxxfilt](https://llvm.org/docs/CommandGuide/llvm-cxxfilt.html) to retrieve demangled names.

**Comment by pablooliveira** [comment]
After looking at the code of `funcInstrument.cpp`, I agree that FuncInstrumentation does not mangle function names.

The only place where we were still calling `demangle` was in vfcInstrument pass.

**Comment by pablooliveira** [comment]
Reopening, sorry we missed https://github.com/verificarlo/verificarlo/blob/35eadb89ed6150e8a09f0143f3f9437d9ea981c7/src/libvfcfuncinstrument/libVFCFuncInstrument.cpp#L505.

Thanks @mistoan for the catch. Could you please remove the if and keep only the mangled name.

**Comment by mistoan** [comment]
I've added the fix in pull request #220 .

**Comment by pablooliveira** [comment]
Merged #220.
