### ISSUE TITLE
vfc_precexp adds dependency to pandas

### ISSUE THREAD

**Issue by mistoan** [verificarlo/verificarlo#211]
The script adds a dependency to pandas python package.
It seems that this isn't documented and the installation example doesn't mention it.

**Comment by pablooliveira** [comment]
Configure macro to check for python modules:

https://www.gnu.org/software/autoconf-archive/ax_python_module.html

**Comment by mistoan** [comment]
Thank you for the hint!
I'll add the necessary checks to the build script.
