### ISSUE TITLE
relicensing Verificarlo

### ISSUE THREAD

**Issue by titeup** [verificarlo/verificarlo#231]
Dear contributors,  @verificarlo/devs 
I just sent an email around to propose the relicensing of Verificarlo (except the mpfr backend).
This discussion started in https://github.com/verificarlo/fuzzy/issues/14
Here is the text of the email:
Dear Verificarlo contributors,

As discussed in PR Verificarlo/Fuzzy #14, we are discussing the idea of relicensing the project. 
Today we are using GPLv3. The historical reason is that we started in 2015 the Verificarlo project around the MPFR backend implementation of M. Frechtling. 
It turns out that Verificarlo expanded in many directions and that this backend is not central or even required in the tool anymore. 
Furthermore, for integration with other tools (such as upstreaming to LLVM or for the Fuzzy docker image) GPL could be limiting. 

After looking around and considering different options we are submitting the following action to your approval:
     1/ Release the original MCA MPFR backend in a separate repository
     2/ Relicense the rest of the code using the LLVM license based on Apache 2.0:    https://foundation.llvm.org/relicensing/LICENSE.txt

To do this relicensing, we need:
     1/ The approval of all verificarlo contributors
     2/ Parts related to missing approval must be dropped or rewriten.    

We enclosed the LLVM license file. We propose to leave one month, until  7th of May 2021, to gather consent for part 1. 
Then depending on our success, evaluate part 2 and schedule our software effort to reach a release with a new license. 
If you consent to a relicense, please answer to this PR/email with the following sentence: 
"I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)"

Feel free to ask question or share your opinion on the PR. (emails is using BCC because some of the contributors did not share their email address publicly) 
We want this process to be smooth and transparent for everyone. If some of us share different opinions, please respect all of them and adopt inclusive, positive, and constructive behavior.

Thank you all,

Eric and Pablo

**Comment by titeup** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by gkiar** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by mistoan** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by yohanchatelain** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by Avaquet** [comment]
I approve the Verificarlo relicensing under the LLVM license based on
Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

Le mar. 6 avr. 2021 à 16:15, Yohan Chatelain ***@***.***> a
écrit :

**Comment by ddavid42** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by pablooliveira** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by Sholde** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by roblim1** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by redfoxp** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by KillianBabilotte** [comment]
I approve the Verificarlo relicensing under the LLVM license based on Apache 2.0 (https://foundation.llvm.org/relicensing/LICENSE.txt)

**Comment by titeup** [comment]
I received the consent of @ojamond by email.

**Comment by titeup** [comment]
Hi, I received all answers, we will start the process next week!
