### ISSUE TITLE
Function names with length beyond current support

### ISSUE THREAD

**Issue by roblim1** [verificarlo/verificarlo#234]
Is there a way to increase the length of the function names read?  In [_interflop_enter_function()](https://github.com/verificarlo/verificarlo/blob/master/src/backends/interflop-vprec/interflop_vprec.c#L760), [vfc_hashmap_get()](https://github.com/verificarlo/verificarlo/blob/master/src/common/vfc_hashmap.c#L211) gets invoked for function_info->id.  If the function name is beyond a certain length, the hash map creation crashes.

This would be great, as I am encountering function names beyond the length that the hash map supports.

Thanks.

**Comment by roblim1** [comment]
Never mind.  Looks like all I needed to do was to change [this](https://github.com/verificarlo/verificarlo/blob/master/src/backends/interflop-vprec/interflop_vprec.c#L628).

Thanks!

**Comment by pablooliveira** [comment]
Interesting. Maybe we should increase the default size. What value would you recommend ?

**Comment by roblim1** [comment]
I've encountered ones with 1826.  I just added another zero in the end, also to [here](https://github.com/verificarlo/verificarlo/blob/0a57a69601073d14b50af4675a78a50af214e698/src/backends/interflop-vprec/interflop_vprec.c#L612).

**Comment by roblim1** [comment]
I've encountered ones with 1826.  Maybe, this could be dynamically sized?

**Comment by roblim1** [comment]
For the record, I've recently encountered a function name size of 4019 characters:

`std::pair<ska::detailv3::sherwood_v3_table<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, ska::detailv3::KeyOrValueHasher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, ska::detailv3::KeyOrValueEquality<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> >, std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> > > >::templated_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> >, bool> ska::detailv3::sherwood_v3_table<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, ska::detailv3::KeyOrValueHasher<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, ska::detailv3::KeyOrValueEquality<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> >, std::allocator<ska::detailv3::sherwood_v3_entry<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> > > >::emplace_new_key<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ska::flat_hash_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> > >::convertible_to_value>(signed char, ska::detailv3::sherwood_v3_entry<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, ska::flat_hash_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue> > >::convertible_to_value&&)
`
