### ISSUE TITLE
Warning when using math library

### ISSUE THREAD

**Issue by Sholde** [verificarlo/verificarlo#245]
Hi,

Last month I wrote a code which using **C math library** and I found a little bug. 

When I didn't link the library I have the normal error due to of undefined reference. But when I linked it on verificarlo command line, `clang` tall me that is `unused`. But it is necessary due to the call of `sqrt` functions.

The code:
```c
#include <math.h>

int main()
{
  sqrt(4);
}
```

Error **without** link:
```shell
$ verificarlo-c sqrt.c
/usr/bin/ld: sqrt.o: in function `main':
sqrt.c:(.text+0x16): undefined reference to `sqrt'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/local/bin/verificarlo: command failed:
/usr/bin/clang @/tmp/tmpw83jhidz
```

Warning **with** link:
```shell
$ verificarlo-c sqrt.c -lm
clang-11: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
clang-11: warning: -lm: 'linker' input unused [-Wunused-command-line-argument]
```

Using `llvm 10` and `clang 11`.

**Comment by yohanchatelain** [comment]
This is a normal behavior, all flags are passed to the compiler and the liker but at compile stage we don't need libraries flags. We could parse them and dispatch them correctly.

**Comment by Sholde** [comment]
Yes, when I said it is a little bug I mean that is not the same behaviour that clang because we have this warning.
