### ISSUE TITLE
Commit 3e6bd62751939bb22ff160ef401b35ce9e49b029 doesn't build

### ISSUE THREAD

**Issue by roblim1** [verificarlo/verificarlo#253]
```
(cpu_p18) roblim1@skylake06:~/repos/verificarlo> make -j8
make  all-recursive
make[1]: Entering directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo'
Making all in src/
make[2]: Entering directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo/src'
Making all in common
make[3]: Entering directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo/src/common'
make[3]: *** No rule to make target 'vfc_probes_f.mod', needed by 'all-am'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC       libvfc_probes_la-vfc_hashmap.lo
  CC       libvfc_probes_la-vfc_probes.lo
  CC       libvprec_tools_la-vprec_tools.lo
  CC       libtinymt64_la-tinymt64.lo
  CC       libvfc_hashmap_la-vfc_hashmap.lo
make[3]: Leaving directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo/src/common'
make[2]: *** [Makefile:431: all-recursive] Error 1
make[2]: Leaving directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo/src'
make[1]: *** [Makefile:516: all-recursive] Error 1
make[1]: Leaving directory '/gpfs/jlse-fs0/users/roblim1/repos/verificarlo'
make: *** [Makefile:403: all] Error 2
```

**Comment by pablooliveira** [comment]
@PurplePachyderm could you please have a look ?
On our autobuilder 3e6bd627 is building but maybe there is an issue on some machines with the fortran modules rules that were added.

**Comment by PurplePachyderm** [comment]
Sure, this might have something to do with the rules to build the Fortran interface not being ignored correctly when flang support is disabled.

**Comment by PurplePachyderm** [comment]
It seems like the rule to install the Fortan header was not inside the `if BUILD_FLANG` clause in `src/common/Makefile.am`. When testing the install without flang support, I probably forgot to `make clean` so I didn't run into the issue since the file was already there. I'll open a PR that should fix the issue and add a small correction to the code of `vfc_ci`.

**Comment by PurplePachyderm** [comment]
Just opened the PR (#255). This should solve the issue but we should probably wait for someone else to confirm before closing it.
