### ISSUE TITLE
Release v0.4.3?

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#264]
Can we release a new version? since major contributions have been added since the last release

**Comment by Sholde** [comment]
I think we should merge #263 (or fix the issue) first in order to have a clean behavior for the `make clean` command.

**Comment by yohanchatelain** [comment]
I think that it does not impact the behaviour of the backends neither the general mechanic. Moreover, it is just an issue with a tracked file that should not be.
