### ISSUE TITLE
Compiling with LLVM-7 and gcc-9 on ubuntu 20.04

### ISSUE THREAD

**Issue by v1j4y** [verificarlo/verificarlo#273]
Hello,

I wanted to report that I was able to compile Verificarlo on my laptop running Ubuntu 20.04 (freshly upgraded) with gcc-9 and LLVM-7. 

However, a small issue appeared which is the following:

```
----X------
configure: error: LLVM is required but program `llvm-config` cannot be found
----X------
```

Which I was able to resolve by adding this to the call to `./configure`

```
 LLVM_CONFIG=/usr/bin/llvm-config-7
```

And the full `./configure` call is:

```
 ./configure --prefix=/home/vijay/.local --with-flang CC=gcc-9 CXX=g++-9  LLVM_CONFIG=/usr/bin/llvm-config-7
```

Did I do this correctly ?
On my side Verificarlo seems to have installed correctly.

Thanks !

**Comment by pablooliveira** [comment]
Hello @v1j4y, thanks for the feedback :pray: Yes this is correct. Unfortunately, on some systems there is no default `llvm-config` on standard path.

Your workaround works. You should also be able to fix it by passing explicitly the LLVM installation path with the following flag:

```
./configure --with-llvm=/usr/lib/llvm-7
```

Does this also works on your environment ?

**Comment by v1j4y** [comment]
Hi @pablooliveira !

Thanks for the reply.
Your solution is cleaner as it now finds `llvm-config` properly here:

```
checking for llvm-config... /usr/lib/llvm-7/bin/llvm-config
```
I confirm that it compiles perfectly with `--with-llvm=/usr/lib/llvm-7`. I'll close this issue.

Best,
 Vijay
