### ISSUE TITLE
Adding tests 

### ISSUE THREAD

**Issue by chdenis** [verificarlo/verificarlo#31]

**Comment by chdenis** [comment]
Help wanted to define the list of  tests.

**Comment by titeup** [comment]
Well, A first and maybe very tricky one could be a more advance backend validation test which measure if there is any significant difference in the samples of two different verificarlo backend. 
This backend should test normal values, but also special cases and denormal, maybe in different phase of the test to give a more complete diagnostic of the differences.
We should also to be able to use similar RD generator with the same seed (to compare backend that should behave the same), or different ones (seed or generator) (to work on the rd generator or backend that should converge to the same measure).

**Comment by chdenis** [comment]
With confidence intervals ?

**Comment by chdenis** [comment]
Test in progress ! Kahan summation and  a chaotic model.

**Comment by titeup** [comment]
Test program are regularly being added, this issue is not relevant anymore
