### ISSUE TITLE
problem of undefined symbol

### ISSUE THREAD

**Issue by Kim1230** [verificarlo/verificarlo#316]
Hello,
I have used verificarlo-c++ to compile the source cpp file and generate an shared object. And when I want to link this .so file to generate executable file. There generates some problems.
undefined symbol: _doubleadd   
undefined symbol: _doublesub  
undefined symbol: _doublemul 
undefined symbol: _doublediv 
undefined symbol: _2xdoublemul
I think because when I link it, I still need to point out some other shared library. Can you tell me which shared library is needed? Thanks!

**Comment by pablooliveira** [comment]
Dear @Kim1230, please make sure you use `verificarlo-c++` for linking. It should solve the issue.

**Comment by Kim1230** [comment]
> Dear @Kim1230, please make sure you use `verificarlo-c++` for linking. It should solve the issue.

Dear@pablooliveira, I make sure that I use this command
`  verificarlo-c++ -fopenmp  -Wno-unknown-pragmas -g  -O2 --std=c++14 -c  -fPIC  -DMPI_NO_CPPBIND=1 -DOMPI_SKIP_MPICXX=1 -DMPICH_SKIP_MPICXX=1 -DHAVE_CONFIG_H -DCORENEURON_BUILD -DHAVE_MALLOC_H -DNRNMPI=1 -DMPI_NO_CPPBIND=1 -DOMPI_SKIP_MPICXX=1 -DMPICH_SKIP_MPICXX=1 -DLAYOUT=0 -DDISABLE_HOC_EXP -DENABLE_SPLAYTREE_QUEUING $(INCLUDES)  $< -o $@ -DNRN_PRCELLSTATE=$(NRN_PRCELLSTATE) -lm   -v
`
And it turns out the result:
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_doubleadd'
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_2xdoubleadd'
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_doublesub'
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_doublemul'
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_doublediv'
ld: x86_64_test/libcorenrnmech.so: undefined reference to `_2xdoublemul'

So, I don't know what is the problem

**Comment by pablooliveira** [comment]
This means probably that `libcorenrnmech.so` has not been linked with verificarlo runtime. Please ensure that all your linking steps go through verificarlo.

Also ensure that the final binary that loads libcorenrnmech.so is also linked with verificarlo.

**Comment by Kim1230** [comment]
> This means probably that `libcorenrnmech.so` has not been linked with verificarlo runtime. Please ensure that all your linking steps go through verificarlo.
> 
> Also ensure that the final binary that loads libcorenrnmech.so is also linked with verificarlo.

Thanks for your quick response. I have modifed it and get another question. When I use the verificarlo-c++  to compile, link to generate execute. When I  add the command `verificarlo-c++ -fPIC  -fopenmp -Wno-unknown-pragmas -g  -O2  -std=c++14 -shared`. At last, it will have the question 
![image](https://user-images.githubusercontent.com/107012598/193014193-9d31d5bb-834c-43a6-a8d6-c79f448be805.png)
And when I delete -fopenmp. It works! Can you tell me what really happend? Thanks

**Comment by pablooliveira** [comment]
It seems -lomp is not found. But I'm not sure exactly what is going on, I would need more context.

Happy you made it works !
