### ISSUE TITLE
FMA and reduce operation support

### ISSUE THREAD

**Issue by titeup** [verificarlo/verificarlo#336]
Hello, 
This issue is a sub-issue of https://github.com/verificarlo/verificarlo/issues/333
Recently LLVM policy has been to set -ffp-contract=on by default. The effectg is to generate FMAs and reduce operation in the IR while before this was happening in the backend.
As an effect, the test_ieee verificarlo fail: -ffp-contract=off is a temprary fix proposed in PR  https://github.com/verificarlo/verificarlo/pull/335
But more importantly the only long-term solution is to add FMA/reduce support.
 @yohanchatelain is working on a PR for it that will close this issue.
**We have to make sure to remove the -ffp-contract flag from verificarlo.in.in afterward before closing.**

**Comment by titeup** [comment]
classified as minor bug since a safe mitigation will be available with PR https://github.com/verificarlo/verificarlo/pull/335

**Comment by yohanchatelain** [comment]
FMA are now supported with #339 but not the reduce operations. I will open an issue for that.
