### ISSUE TITLE
Unexpected behavior for VERIFICARLO_PRECISION=0

### ISSUE THREAD

**Issue by yohanchatelain** [verificarlo/verificarlo#41]
I open a ticket for the behavior of VERIFICARLO_PRECISION when is set to 0.
We expected to have all bits noised but it turns out that no noise is added.
When verbose mode is activated, verificarlo outputs : 

> VERIFICARLO_PRECISION invalid value provided, defaulting to default

**Comment by titeup** [comment]
Well it is difficult to interpret the zero. Would that mean all the pseudo mantissa bits are impacted but not the order of magnitude (exponent)
Or the exponent last bits is noised to change the implicit mantissa bit, or the exponent is totaly noised, or even the signed might change (ie the FP number is replaced by a random FP value)
What about special values (inf, nan, zero, etc.)?
I think we should discuss further that special case. 

What would you expect yourself for your case?

**Comment by yohanchatelain** [comment]
Yes I think we should discuss but for my case, I expect that all mantissa bits are noised and not the order of magnitude.

**Comment by titeup** [comment]
You mean pseudo mantissa I suppose, but I got the idea.
Maybe I am wrong but there is 52 explicit bit stored, when you ask 53 precision to verificarlo, only the last bit change. When you ask 1 all should change.
I remember we had sort of this dicussion already with Pablo when debugging the function to set the noise magnitude (exponent). Didn’t remember what was the output.
I am passing by your lab tomorow 11th Jan (as you should know…) and eventually the day after. We will sort it out then.

**Comment by titeup** [comment]
done
