### ISSUE TITLE
Newer LLVM support

### ISSUE THREAD

**Issue by cheche19** [verificarlo/verificarlo#62]
Currently verificarlo support LLVM up to version 3.8.1.
LLVM current version is 6.0, and most modern linux distrubution use version 4.0+.
Do you think that verificarlo can be updated to support newer llvm ?

Thanks.

**Comment by pablooliveira** [comment]
Supporting newer LLVM versions is not difficult; but requires some work. Usually it requires minor adaptations to the libVFCInstrument library (https://github.com/verificarlo/verificarlo/blob/master/src/libvfcinstrument/libVFCInstrument.cpp).

Currently some work is being planned to merge and finish the VeriTracer branch; so I would prefer to wait before upgrading master to LLVM 6.0.

Do you have any urgent needs for this, in that case we could discuss how to prioritize it? Also, if you want to help writing a PR we could help you.
