### ISSUE TITLE
configure failure during checking can compile with and link with LLVM(all)...

### ISSUE THREAD

**Issue by hbrunie** [verificarlo/verificarlo#83]
Hello,

the configure test failed to compile the simple main test.
I used LLVM 4.0.1 compiled with gcc 4.8.5.
It seems that some flags are missing.

I corrected it changing line 104 of file m4/ax_llvm.m4
104   LDFLAGS="$LDFLAGS -stdlib=libstdc++ -pthread -ltinfo -ldl"

Nevertheless, I'm not sure this is the best way to correct this "bug".
Thanks for your work,
 Hugo

**Comment by pablooliveira** [comment]
I think this should be fixed in #91, but it's hard to reproduce your environment. Please feel free to reopen if there is still a bug and many thanks for the report.
