### ISSUE TITLE
Get Zenodo DOI?

### ISSUE THREAD

**Issue by gkiar** [verificarlo/verificarlo#95]
It would be nice to have a citable DOI for each version of the code (alongside the pre-print/soon to be published paper), to more easily identify the specific build that is used in a given dependency. I noticed you just made a version, and Zenodo can automatically hook in creating a fresh DOI each time to you do this. Instructions pasted below, in case you're unfamiliar with this integration:

https://guides.github.com/activities/citable-code/

**Comment by pablooliveira** [comment]
Good idea ! Zenodo is now linked to verificarlo's github. Thanks for the detailed discussion.
Unfortunately, it is not possible to tag old releases. Nevertheless next release will be tagged automatically.

To get a doi for the pre-print, we will either do a minor version release before the deadline if we have new code changes; or we will manually tag release 0.2.2 by uploading a release tarball.
